tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'codeclimate/formulae'
tap 'fisherman/tap'
tap 'homebrew/binary'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/fuse'
tap 'homebrew/games'
tap 'homebrew/services'
tap 'homebrew/x11'
tap 'srcclr/srcclr'
brew 'aalib'
brew 'ack'
brew 'pkg-config'
brew 'readline'
brew 'icu4c'
brew 'sqlite'
brew 'makedepend'
brew 'openssl', args: ['universal']
brew 'aircrack-ng'
brew 'antigen'
brew 'antiword'
brew 'xz'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'libpng', args: ['universal']
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'pixman'
brew 'cairo'
brew 'git'
brew 'gobject-introspection'
brew 'atk'
brew 'autoconf'
brew 'automake'
brew 'babl'
brew 'bar'
brew 'bash'
brew 'bash-completion'
brew 'bdw-gc'
brew 'betty'
brew 'binutils'
brew 'boost'
brew 'boxes'
brew 'calc'
brew 'ccextractor'
brew 'cheat'
brew 'sphinx-doc'
brew 'cmake'
brew 'gmp'
brew 'coreutils'
brew 'cowsay'
brew 'cscope'
brew 'ctorrent'
brew 'libidn'
brew 'libressl'
brew 'libssh2'
brew 'curl'
brew 'libsodium'
brew 'zeromq'
brew 'czmq'
brew 'daemon'
brew 'dbus'
brew 'ddrescue'
brew 'dialog'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'e2fsprogs'
brew 'libtasn1', args: ['universal']
brew 'nettle'
brew 'gnutls'
brew 'jpeg', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'gdk-pixbuf'
brew 'libcroco'
brew 'harfbuzz'
brew 'pango'
brew 'libtool', args: ['universal']
brew 'libepoxy'
brew 'hicolor-icon-theme'
brew 'gsettings-desktop-schemas'
brew 'jasper', args: ['universal']
brew 'gtk+3'
brew 'librsvg'
brew 'little-cms2', args: ['universal']
brew 'webp', args: ['universal']
brew 'gd', args: ['universal']
brew 'libwmf'
brew 'perl'
brew 'imagemagick'
brew 'emacs'
brew 'faac'
brew 'x264'
brew 'lame'
brew 'xvid'
brew 'libssh'
brew 'ffmpeg'
brew 'pcre2'
brew 'fish'
brew 'flac'
brew 'fontforge'
brew 'mpfr'
brew 'gawk'
brew 'libmpc'
brew 'isl'
brew 'gcc'
brew 'gdbm'
brew 'getmail'
brew 'gforth'
brew 'go'
brew 'gh'
brew 'gist'
brew 'git-secrets'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'gnupg'
brew 'gtk+'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'gnupg2'
brew 'python'
brew 'pygobject'
brew 'py2cairo'
brew 'pygtk'
brew 'gtk-mac-integration'
brew 'help2man'
brew 'heroku'
brew 'lua'
brew 'highlight'
brew 'htop-osx'
brew 'subversion'
brew 'mysql'
brew 'hydra', args: ['with-libidn', 'with-libssh', 'with-subversion']
brew 'i2p'
brew 'imessage-ruby'
brew 'libav'
brew 'libevent'
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'libxml2'
brew 'libplist'
brew 'usbmuxd'
brew 'libimobiledevice'
brew 'libuv'
brew 'libyaml'
brew 'links', args: ['with-jpeg', 'with-libressl', 'with-librsvg', 'with-libtiff', 'with-x11']
brew 's-lang'
brew 'midnight-commander'
brew 'nmap'
brew 'node'
brew 'platformio'
brew 'portaudio'
brew 'portmidi'
brew 'postgresql'
brew 'ppss'
brew 'proxychains-ng'
brew 'pv'
brew 'qt'
brew 'python3'
brew 'sip'
brew 'pyqt'
brew 'rainbarf'
brew 'ruby-build'
brew 'rbenv'
brew 'red'
brew 'rmtrash'
brew 'safe-rm'
brew 'sane-backends', args: ['universal']
brew 'sdl2'
brew 'sl'
brew 'snow'
brew 'spoof-mac'
brew 'ssh-copy-id'
brew 'tag'
brew 'tcsh'
brew 'terminal-notifier'
brew 'tidy-html5'
brew 'tmux'
brew 'tor'
brew 'tree'
brew 'unar'
brew 'vim', args: ['with-override-system-vi']
brew 'w3m'
brew 'wget'
brew 'wine'
brew 'youtube-dl'
brew 'zsh'
brew 'fisherman/tap/fisherman'
brew 'homebrew/binary/rebol-core'
brew 'homebrew/boneyard/powerline'
brew 'homebrew/dupes/gperf'
brew 'homebrew/dupes/grep', args: ['with-default-names']
brew 'homebrew/dupes/m4'
brew 'homebrew/dupes/make'
brew 'homebrew/dupes/ncurses'
brew 'homebrew/dupes/nano'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/screen'
brew 'homebrew/dupes/srm'
brew 'homebrew/games/gnu-chess', args: ['with-book']
brew 'homebrew/games/mame'
brew 'homebrew/x11/openmotif'
brew 'homebrew/x11/xpdf'
brew 'homebrew/x11/xplot'
brew 'srcclr/srcclr/srcclr'
